#!/bin/bash

NAME=$1
OPTION=$2
SUMMARY=$3


main () {
  OPTION=$1
  NAME=$2
  SUMMARY=$3
  case $OPTION in
    Python|python|Python3|python3)
      python_repo "$NAME" "$SUMMARY"
      ;;
    C|c)
      c_repo "$NAME" "$SUMMARY"
      ;;
    C|c)
      latex_repo "$NAME" "$SUMMARY"
      ;;
    *)
      echo Expected "Python3", or "C".
      ;;
  esac
  common_repo_actions
}


common_repo_actions() {
  git init
  git add .
  git commit --message="INIT: with TheOrganist24 repo generator."
  git branch -m development
}


python_repo () {
  NAME=$1
  SUMMARY=$2
  echo Creating Python3 repository "$NAME"
  common_files "$NAME" "$SUMMARY"
}


c_repo () {
  echo Creating C repository "$NAME"
  common_files "$NAME" "$SUMMARY"
}


common_files () {
  NAME=$1
  SUMMARY=$2
  
  # create README
  cat << EOF > README.md
![TheOrganist24 Code](https://hosted.courtman.me.uk/img/logos/theorganist24_banner_code.png "TheOrganist24 Code")

# $NAME
> $SUMMARY

## Getting Started
EOF

  # add placeholders for other standard files
  touch MakeFile .gitignore LICENSE
  
  # create common directories
  mkdir --parents img/src
  touch img/src/.gitkeep
}



main "$OPTION" "$NAME" "$SUMMARY"
